Traceback (most recent call last):
  File "/usr/share/miniconda/envs/qir-book/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/qir-book/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/qir-book/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/qir-book/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/qir-book/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/qir-book/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/qir-book/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/qir-book/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
with open('qutip_program.ll', 'w') as file:
    file.write(circuit_to_qir(teleportation, "text"))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNotImplementedError[0m                       Traceback (most recent call last)
Cell [0;32mIn[8], line 2[0m
[1;32m      1[0m [38;5;28;01mwith[39;00m [38;5;28mopen[39m([38;5;124m'[39m[38;5;124mqutip_program.ll[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mw[39m[38;5;124m'[39m) [38;5;28;01mas[39;00m file:
[0;32m----> 2[0m     file[38;5;241m.[39mwrite([43mcircuit_to_qir[49m[43m([49m[43mteleportation[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mtext[39;49m[38;5;124;43m"[39;49m[43m)[49m)

File [0;32m~/work/qir-book/qir-book/qir-book/tutorials/qir-emission/qutip/qutip_qip_qir.py:213[0m, in [0;36mcircuit_to_qir[0;34m(circuit, format, module_name)[0m
[1;32m    207[0m         builder[38;5;241m.[39mmz(
[1;32m    208[0m             module[38;5;241m.[39mqubits[op[38;5;241m.[39mtargets[[38;5;241m0[39m]],
[1;32m    209[0m             module[38;5;241m.[39mresults[op[38;5;241m.[39mclassical_store],
[1;32m    210[0m         )
[1;32m    212[0m     [38;5;28;01melse[39;00m:
[0;32m--> 213[0m         [38;5;28;01mraise[39;00m [38;5;167;01mNotImplementedError[39;00m(
[1;32m    214[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mInstruction [39m[38;5;132;01m{[39;00mop[38;5;132;01m}[39;00m[38;5;124m is not implemented in the QIR base [39m[38;5;124m"[39m
[1;32m    215[0m             [38;5;241m+[39m [38;5;124m"[39m[38;5;124mprofile and may require a custom declaration.[39m[38;5;124m"[39m
[1;32m    216[0m         )
[1;32m    218[0m [38;5;28;01mif[39;00m fmt [38;5;241m==[39m QirFormat[38;5;241m.[39mTEXT:
[1;32m    219[0m     [38;5;28;01mreturn[39;00m module[38;5;241m.[39mir()

[0;31mNotImplementedError[0m: Instruction Gate(SNOT, targets=[1], controls=None, classical controls=None, control_value=None) is not implemented in the QIR base profile and may require a custom declaration.
NotImplementedError: Instruction Gate(SNOT, targets=[1], controls=None, classical controls=None, control_value=None) is not implemented in the QIR base profile and may require a custom declaration.

